sonar.projectKey=tsiryRIVOSON_smartfood-api
sonar.organization=tsiryrivoson
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=index.js,__tests__/**