name: Controle Qualité

on:
  push:
    branches:
      - main

jobs:
  qualite:
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
      
      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Installer les dépendances
        run: npm install
      
      - name: Lancer ESLint
        run: npx eslint index.js
      
      - name: Analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}